const soapBody = `<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://rgwspublic2.ws.gsis.gr/">
  <soapenv:Header/>
  <soapenv:Body>
    <ws:rgWsPublicAfmMethod>
      <RgWsPublicInputRt_in>
        <afm>${afm}</afm>
        <asOnDate></asOnDate>
      </RgWsPublicInputRt_in>
      <RgWsPublicBasicRt_out>
        <afm/>
        <doyDescr/>
        <onomasia/>
        <commerTitle/>
        <legalStatusDescr/>
        <registDate/>
        <stopDate/>
        <postalAddress/>
        <postalAddressNo/>
        <postalZipCode/>
        <postalAreaDescription/>
        <phone/>
        <firmFlag/>
        <deactivationFlag/>
        <deactivationFlagDescr/>
        <kindOfPerson/>
      </RgWsPublicBasicRt_out>
      <arrayOfRgWsPublicFirmActRt_out/>
      <arrayOfRgWsPublicRecRd_out/>
      <pCallSeqId/>
      <pErrorRec_out>
        <errorCode/>
        <errorDescr/>
      </pErrorRec_out>
      <username>${AADE_USERNAME}</username>
      <password>${AADE_PASSWORD}</password>
    </ws:rgWsPublicAfmMethod>
  </soapenv:Body>
</soapenv:Envelope>`;

